<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('products')->truncate();
        DB::table('products')->insert([
            [
                'id' => 1,
                'name' => 'Pioneer',
                'labelName' => "Dharma Studio",
                'price' => 22,
                'weight' => '12GB',
                'category' => 3,
                'labelTitle' => "Dharma Studio",
                'Tag' => "Futuristic Beatbox",
                'thumbnail' => "https://www.dharmaworldwide.com/wp-content/uploads/2022/08/Pioneer2-500x500.jpg",
                'description' => 'The ‘Pioneer’ futuristic beatbox grooves sound pack is a unique collection of beatbox samples created by ROMO . ROMO is a beatboxer, music producer, sound designer, DJ, and music journalist . All samples have been created using ROMO’s voice . This pack is filled with vocals, vocals scratches, synths, loops, and various FX to help add a futuristic beatbox sound to your productions .',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 2,
                'name' => 'Revealed Tech House Essentials Vol. 2',
                'labelName' => 'Revealed',
                'price' => 24,
                'weight' => '12GB',
                'category' => 1,
                'labelTitle' => 'Revealed',
                'Tag' => 'TECH HOUSE',
                'thumbnail' => 'https://www.revealedrecordings.com/uploads/image/634823e2241209b42406a4b3.jpg',
                'description' => 'Revealed Tech House Essentials Vol . 2 is a collection of over 300 sample loops and MIDI – filled with the fundamental tools to create Tech House . Divided into 15 categories, you will find an array of Fills, Drums, Top Loops, Bass Loops, Synth Loops, SFX, Percussion, and more! To speed up your workflow, all samples are labeled by their root key, if a discernible pitch was defined. Revealed Tech House Essentials Vol. 2 is packed with a comprehensive and carefully selected collection of sounds to help take your Tech House productions to the next level! Reveal Yourself.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 3,
                'name' => 'Revealed Serum Techno Kicks Vol . 1',
                'labelName' => 'Revealed',
                'price' => 14,
                'weight' => '12GB',
                'category' => 2,
                'labelTitle' => 'Revealed',
                'Tag' => 'BIG ROOM,TECHNO',
                'thumbnail' => 'https://www.revealedrecordings.com/uploads/image/632d9c1afd519bdd88064071.jpg',
                'description' => 'Finding the perfect kick can be difficult . Not anymore!Revealed Serum Techno Kicks Vol . 1 is a toolkit filled with 44 presets where you will have all the source sounds to craft your own signature kicks . Each preset has modwheel and macros assigned, so you can shape the core characteristics of your techno bass drums to fit directly into your track . Additionally, included are 200 + macro shaping one - shots so you can quickly drag and drop, sculpt and shape, and mix and mangle a huge variety of inspiring kicks . With Revealed Serum Techno Kicks Vol . 1, you will have the tools to customize your own signature Techno kicks! Reveal Yourself .',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 4,
                'name' => 'Revealed Serum Ultimate Bass Vol . 2',
                'labelName' => 'Revealed',
                'price' => 29,
                'weight' => '12GB',
                'category' => 2,
                'labelTitle' => 'Revealed',
                'Tag' => 'ACID, BASS, BASS HOUSE,BIG ROOM,DUBSTEPELECTRO',
                'thumbnail' => 'https://www.revealedrecordings.com/uploads/image/632402c990517075de0d6c64.jpg',
                'description' => 'Revealed Serum Ultimate Bass Vol . 2 is a collection of 100 of the most modern - day Bass presets for your next Techno, Big Room, Tech House, Bass House, and Progressive tracks! You will find a large and diverse selection of powerful bass sounds . Additionally, each preset has modwheel controls and all 4 macros programmed to give you more control shaping your sound . Reveal Yourself .',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 5,
                'name' => 'Revealed Progressive Arps Vol . 3',
                'labelName' => 'Revealed',
                'price' => 50,
                'weight' => '10GB',
                'category' => 1,
                'labelTitle' => 'Revealed',
                'Tag' => 'PROGRESSIVE HOUSE',
                'thumbnail' => 'https://www.revealedrecordings.com/uploads/image/6319fd4423c98a71fe066225.jpg',
                'description' => 'Revealed Progressive Arps Vol . 3 is a collection of 50 MIDI and 160 + Arp Loops ready to use as support harmonies or main leads in your productions . Each MIDI has multiple WAV loop expressions, labeled by key, so you can test out a variety of melodic melodies right away . or, you can take your favorite MIDI melodies and reconstruct them exactly how you want using your preferred presets!',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 6,
                'name' => 'Revealed Spire 303 Sequences Vol . 3',
                'labelName' => 'Revealed',
                'price' => 113,
                'weight' => '14GB',
                'category' => 3,
                'labelTitle' => 'Revealed',
                'Tag' => 'ACID,PSY TRANCE,TECHNO',
                'thumbnail' => 'https://www.revealedrecordings.com/uploads/image/6311a0f360448fa44706c656.jpg',
                'description' => 'Revealed Spire 303 Sequences Vol . 3 is a collection of 50 presets and 450 acid loops ready to inject into your next track . Hold a note and let the programmed sequence play or uncheck the arpeggiator and write your own acid melodies! Among every preset having modwheel assignments, each preset is assigned all four macro controls, both programmed to give you quick creative modulation options to shape your sound just the way you want it . Additionally, each 303 sequence has been sampled multiple times with macro shaping expressions, sorted by key, in multiple BPMs(105, 128, 140) - for quick use and inspiration! With Revealed Spire 303 Sequences Vol . 3, you will have a suite of creative tools made for producers looking for a quality Acid, Techno, and Psy Trance sound . Reveal Yourself .',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 7,
                'name' => 'KSHMR Presents Zafrir is World Instruments Vol . 1',
                'labelName' => 'Dharma Studio',
                'price' => 29,
                'weight' => '14GB',
                'category' => 3,
                'labelTitle' => 'Dharma Studio',
                'Tag' => 'Ethnic',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/10/zafrir-pack-art-1-500x500.jpg',
                'description' => 'KSHMR embarks on a new journey with legendary producer Zafrir, to bring you a unique collection of ethnic instruments and vocals to incorporate into your productions . Samples in Zafrir’s World Instruments Vol . 1 span across the globe from the far east of China, through the Middle East, Africa & Europe, as well as the Americas . This pack is carefully crafted to capture the magic of niche instruments such as the Chinese bamboo flute, the Native American flute, flamenco guitars, the Turkish clarinet, the arghoul, mandolins, the Greek baglama, Balkan guitars, darbukas, timbales, and many more . Explore further with the mesmerizing vocal hooks and chants of Africa, Arabia, India, Bulgaria, Romania & more . Capture the essence of the world in your music today, with Zafrir’s World Instruments Vol . 1.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [

                'id' => 8,
                'name' => 'Sounds of KSHMR Vol . 4 Complete Edition',
                'labelName' => 'Dharma Studio',
                'price' => 99,
                'weight' => '14GB',
                'category' => 1,
                'labelTitle' => 'Dharma Studio',
                'Tag' => 'Sounds of KSHMR',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/05/Sounds-of-KSHMR-Vol-4-Artwork-Complete-1.jpg',
                'description' => 'Sounds of KSHMR Vol . 4 Complete Edition is the latest installment in KSHMR’s legendary sound pack libraries . Explore over 7,000 new sounds he’s made with sound designers, instrumentalists, and vocalists from around the world . This pack also includes contributions from KSHMR’s friends such as Armin Van Buuren, Hardwell, R3HAB, W & W, Zedd & more . The Complete Edition is fully equipped with over 7,000 sounds including the 750 sounds that are also available on Splice . Your purchase of the Complete Edition includes access to a bonus download of the Splice Edition, which includes copies of the 750 samples organized and named in the Splice format .',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'id' => 9,
                'name' => 'Operator',
                'labelName' => 'Dharma Studio',
                'price' => 39,
                'weight' => '14GB',
                'category' => 2,
                'labelTitle' => 'Dharma Studio',
                'Tag' => 'Modern House',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/07/Operator-500x500.jpg',
                'description' => 'The Operator pack is filled with funky and groovy house samples to add a modern house style to your music productions . Includes: -11 Bass Loops - 1 FX - 13 Instrumental Loops - 5 Percussion Loops - 3 Vocal Loops - 7 Bass Shots - 7 Claps - 14 Hats - 15 Kicks - …',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 10,
                'name' => 'Fuse',
                'labelName' => 'Dharma Studio',
                'price' => 65,
                'weight' => '14GB',
                'category' => 3,
                'labelTitle' => 'Dharma Studio',
                'Tag' => 'Big Room',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/06/FuseBigRoom-500x500.jpg',
                'description' => 'The Fuse Big Room Sound Pack is the ultimate tool in your arsenal to add the classic big room feel to any of your productions . All Dharma sound packs are 100 % royalty - free and compatible with any DAW . Includes: -20 Synths - 12 Loops - 10 Fills - 60 Drums - 18 FX',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 11,
                'name' => 'Messiah',
                'labelName' => 'Dharma Studio',
                'price' => 91,
                'weight' => '14GB',
                'category' => 2,
                'labelTitle' => 'Dharma Studio',
                'Tag' => 'Afro House',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/06/Messiah-500x500.jpg',
                'description' => 'TExplore the rich sounds of Afro House with Messiah, a sound pack designed to add house - heavy elements to your production with an afro flair . All Dharma sound packs are 100 % royalty - free and compatible with any DAW . Includes: -20 Synths - 20 Loops - 5 Fills - 55 Drums - 20 FX ',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 12,
                'name' => 'Crystallize',
                'labelName' => 'Dharma Studio',
                'price' => 20,
                'weight' => '14GB',
                'category' => 2,
                'labelTitle' => 'Dharma Studio',
                'Tag' => 'Hardstyle',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/06/Crystallize-500x500.jpg',
                'description' => 'Dharma Studio Crystallize is a hardstyle sound pack featuring samples that will elevate your production with energy and power, capturing the essence of hardstyle . All Dharma sound packs are 100 % royalty - free and compatible with any DAW . Includes: -7 Melodic Loops - 21 Synths - 15 Loops - 55 Drums - 26 FX',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 13,
                'name' => 'Oxygen',
                'labelName' => 'Ultrasonic',
                'price' => 20,
                'weight' => '14GB',
                'category' => 3,
                'labelTitle' => 'Ultrasonic',
                'Tag' => 'STMPD Sample Pack',
                'thumbnail' => 'https://static.wixstatic.com/media/a84bb2_0f7f6bb0e0c743048e3e450ecbb1675d~mv2.png/v1/fill/w_606,h_530,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/ultrasonic%20oxygen%20stmpd%20rcrds%20sample%20pack.png',
                'description' => 'The Oxygen STMPD Sample Pack is your one - stop - shop for everything you need to lock in those hard - to - find Presets and Samples . Perfect for music producers of all genres, the library has enough content to supply you with a lifetime of inspiration.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 14,
                'name' => 'VIBRATIONS',
                'labelName' => 'Ultrasonic',
                'price' => 55,
                'weight' => '15GB',
                'category' => 1,
                'labelTitle' => 'Ultrasonic',
                'Tag' => 'Ambiance Sample Pack',
                'thumbnail' => 'https://static.wixstatic.com/media/a84bb2_499ded14eb64459fa3e8c1e640011388~mv2.png/v1/fill/w_2000,h_1750,al_c/a84bb2_499ded14eb64459fa3e8c1e640011388~mv2.png',
                'description' => 'Having some good Ambiance Samples can help you fill - up the empty space in your tracks . Vibrations contains 100 Atmospheric Samples that will take your listeners to a new dimension and make your tracks sound a lot fuller . ​',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 15,
                'name' => 'Presence',
                'labelName' => 'Ultrasonic',
                'price' => 45,
                'weight' => '15GB',
                'category' => 2,
                'labelTitle' => 'Ultrasonic',
                'Tag' => 'EDM Kicks Sample Pack',
                'thumbnail' => 'https://static.wixstatic.com/media/a84bb2_7187818c667b48ff97bd62c841ecf688~mv2.png/v1/fill/w_700,h_614,al_c,q_90,usm_0.66_1.00_0.01,enc_auto/Ultrasonic%20Presence%20EDM%20Kicks%20Sample%20Pack.png',
                'description' => 'Mixing the low end is something that probably most producers out there spend quite a lot of time with, considering it is representing the sole weight and power of your song . That is why Presence comes with 100 High - Quality Kick Drum Samples compatible with most EDM Genres like: Progressive House, Slap House, Deep House,Tech House, Future Bounce, Future House and many more!​',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 16,
                'name' => 'Slap house',
                'labelName' => 'Ultrasonic',
                'price' => 54,
                'weight' => '16GB',
                'category' => 3,
                'labelTitle' => 'Ultrasonic',
                'Tag' => 'Essentials Vol.1',
                'thumbnail' => 'https://static.wixstatic.com/media/a84bb2_a13feeb24c6349ccb9b0e5e676bc6155~mv2.png/v1/fill/w_1800,h_1471,al_c/a84bb2_a13feeb24c6349ccb9b0e5e676bc6155~mv2.png',
                'description' => 'Most of us have experienced the frustration of searching for that specific sound amongst thousands of presets to no avail . Well here is your chance to get used to our new sounds and take control over YOUR creativity . With Ultrasonics “Slap House Sample Pack . ” You have over 750 Sounds & Samples to play with as soon as you purchase! Stop making excuses and create with us TODAY!',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 17,
                'name' => 'Regardless',
                'labelName' => 'Ultrasonic',
                'price' => 56,
                'weight' => '11GB',
                'category' => 1,
                'labelTitle' => 'Ultrasonic',
                'Tag' => 'Deep House Sample Pack',
                'thumbnail' => 'https://static.wixstatic.com/media/a84bb2_61b010dea05f4584973a7681b7364cc6~mv2.png/v1/fit/w_500,h_500,q_90/file.png',
                'description' => 'Fuel your ambitions with this specifically designed Sample Pack to take your Deep House tracks to the next level . This pack includes 150 Presets, 475 Drum Loops & One Shots, 5 fully produced Projects in Ableton, Fl Studio & Logic Pro X, Vocal Samples and more! This package will push your creative boundaries and inspire new ideas .',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 18,
                'name' => 'ETERNITY',
                'labelName' => 'Ultrasonic',
                'price' => 16,
                'weight' => '11GB',
                'category' => 2,
                'labelTitle' => 'Ultrasonic',
                'Tag' => 'Future Bounce Sample Pack',
                'thumbnail' => 'https://i1.sndcdn.com/artworks-qm1ReTbGztOfsXom-Dm5kWA-t500x500.jpg',
                'description' => 'Wake up to a mix of carefully crafted sounds that are meant to inspire you . This Future Bounce Sample Pack includes 350 Presets plus 335 One Shots & Drum Loops inspired by some of the most cutting - edge producers around the world that will help you make Amazing & Unique music INSTANTLY',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 19,
                'name' => 'Progressive house',
                'labelName' => 'Ultrasonic',
                'price' => 37,
                'weight' => '12GB',
                'category' => 3,
                'labelTitle' => 'Ultrasonic',
                'Tag' => 'Sample Pack',
                'thumbnail' => 'https://static.wixstatic.com/media/a84bb2_35e6ccc22c9840eebad7ac7db10b9b25~mv2.png/v1/fit/w_500,h_500,q_90/file.png',
                'description' => 'Wake up to a mix of carefully crafted sounds that are meant to inspire you . This Future Bounce Sample Pack includes 350 Presets plus 335 One Shots & Drum Loops inspired by some of the most cutting - edge producers around the world that will help you make Amazing & Unique music INSTANTLY',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 20,
                'name' => 'EDM Essentilas',
                'labelName' => 'Ultrasonic',
                'price' => 33,
                'weight' => '12GB',
                'category' => 3,
                'labelTitle' => 'Ultrasonic',
                'Tag' => 'Vol.1',
                'thumbnail' => 'https://static.wixstatic.com/media/a84bb2_27ccd135de2a452d955b688986f8ee20~mv2.png/v1/fill/w_608,h_510,al_c/a84bb2_27ccd135de2a452d955b688986f8ee20~mv2.png',
                'description' => 'Wake up to a mix of carefully crafted sounds that are meant to inspire you . This Future Bounce Sample Pack includes 350 Presets plus 335 One Shots & Drum Loops inspired by some of the most cutting - edge producers around the world that will help you make Amazing & Unique music INSTANTLY',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 21,
                'name' => 'Ultrasonic - Future Bass',
                'labelName' => 'Ultrasonic',
                'price' => 36,
                'weight' => '12GB',
                'category' => 3,
                'labelTitle' => 'Ultrasonic',
                'Tag' => 'Sample Pack Vol.1',
                'thumbnail' => 'https://2.bp.blogspot.com/-pxD7PaC2qTs/XdasmvRterI/AAAAAAAAUco/ex5PO-Byl60Bi7U5kU5vcs6Vju6rKW9HACLcBGAsYHQ/s1600/Ultrasonic%2BFuture%2BBass%2BSample%2BPack%2BVol.png',
                'description' => 'Wake up to a mix of carefully crafted sounds that are meant to inspire you . This Future Bounce Sample Pack includes 350 Presets plus 335 One Shots & Drum Loops inspired by some of the most cutting - edge producers around the world that will help you make Amazing & Unique music INSTANTLY',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 22,
                'name' => 'MARTIN GARRIX',
                'labelName' => 'Ultrasonic',
                'price' => 45,
                'weight' => '12GB',
                'category' => 1,
                'labelTitle' => 'Ultrasonic',
                'Tag' => 'Essentials Vol.1',
                'thumbnail' => 'https://static.wixstatic.com/media/a84bb2_027ad5e8eea54d12a51fbdb172746815~mv2.png/v1/fill/w_2000,h_1750,al_c/a84bb2_027ad5e8eea54d12a51fbdb172746815~mv2.png',
                'description' => 'Wake up to a mix of carefully crafted sounds that are meant to inspire you . This Future Bounce Sample Pack includes 350 Presets plus 335 One Shots & Drum Loops inspired by some of the most cutting - edge producers around the world that will help you make Amazing & Unique music INSTANTLY',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 23,
                'name' => 'Waverider',
                'labelName' => 'Dharma Studio',
                'price' => 42,
                'weight' => '16GB',
                'category' => 3,
                'labelTitle' => 'Dharma Studio',
                'Tag' => 'Dharma Studio, Melodic Bass',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/04/WaveriderMelodicBass-1-scaled.jpg',
                'description' => 'WaWaverider is the ultimate melodic bass sound pack, engineered to add soul and character to your electronic music productions . This pack is filled with various samples to help elevate your sound . Includes: -50 drums - 10 Fills - 25 FX - 15 Loops - 20 Synths',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 24,
                'name' => 'Maestro',
                'labelName' => 'Dharma Studio',
                'price' => 42,
                'weight' => '16GB',
                'category' => 3,
                'labelTitle' => 'Dharma Studio',
                'Tag' => 'Brazilian Bass, Dharma Studio, Sample Pack',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/04/MaestroBrasillianBass-1.jpg',
                'description' => 'Get down and funky with this Brazilian bass focused sample pack, created to help you add bounce and attitude to your mix . Includes: -26 Basses - 51 Drums - 9 FX - 18 Instruments - 8 Vocals  ',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 25,
                'name' => 'Astral',
                'labelName' => 'Dharma Studio',
                'price' => 42,
                'weight' => '16GB',
                'category' => 3,
                'labelTitle' => 'Dharma Studio',
                'Tag' => 'Nu - Disco, Dharma Studio, Sample Pack',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/04/WaveriderMelodicBass-1-scaled.jpg',
                'description' => 'This Nu - Disco sound pack will be the perfect groovy addition to your production arsenal, giving your sound the flavor and style of the nu - disco genre . All Dharma sound packs are 100 % royalty - free and compatible with any DAW .',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 26,
                'name' => 'Dubstep Bass for Serum Vol . 1',
                'labelName' => 'Dharma Studio',
                'price' => 111,
                'weight' => '14GB',
                'category' => 1,
                'labelTitle' => 'Dharma Studio',
                'Tag' => 'Bass, Dubstep',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/03/Dubstep-Bass-For-Serum-500x500.jpg',
                'description' => 'This preset pack was made for fans of the hard - hitting dubstep and bass tracks entrenched in the electronic music scene today . Filled with powerful basses and wavetables, this preset pack will give your project the classic dubstep punch needed for the bass stage . Includes: -15 Basses - 19 Wavetables',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 27,
                'name' => 'Psytrance Vol . 1',
                'labelName' => 'Dharma Studio',
                'price' => 42,
                'weight' => '16GB',
                'category' => 3,
                'labelTitle' => 'Dharma Studio',
                'Tag' => 'Psytrance',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/03/Psytrance_001-500x500.png',
                'description' => 'Psytrance Vol.1 is primed and ready to take you to worlds beyond . This pack is full of high energy sounds inspired by the hardcore psytrance scene . All Dharma sound packs are 100 % royalty - free and compatible with any DAW .',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 28,
                'name' => 'Lasers',
                'labelName' => 'Dharma Studio',
                'price' => 101,
                'weight' => '16GB',
                'category' => 1,
                'labelTitle' => 'Dharma Studio',
                'Tag' => 'Big Room',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/03/Lasers.jpg',
                'description' => '‘Lasers’ is Serum preset pack filled with basses, chords, leads, plucks, and pads to pack your production with power and punch, giving it the ultimate big room sound . Inspired by the top big room tracks in the industry . All Dharma sound packs are 100 % royalty - free and compatible with any DAW .',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 29,
                'name' => 'FSTVL ANTHMZ',
                'labelName' => 'Dharma Studio',
                'price' => 145,
                'weight' => '16GB',
                'category' => 1,
                'labelTitle' => 'Dharma Studio',
                'Tag' => 'EDM, BASS MUSIC, Bass, Cinematic / FX, HIP - HOP / R & B, ADSR',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/03/ADSR-FSTVL-ANTHMZ-Cover-1.jpg',
                'description' => 'Spring is here with summer right around the corner and the production team at ADSR have whipped up over 600MB of anthemic content in their latest release FSTVL ANTHMZ . This pack comes to you highly inspired by artists such as Calvin Harris, Vinai, Martin Garrix, Alesso, R3hab, Joey Dale & KSHMR . This release comes with over 200 audio samples of searing synth leads, pumping basslines, tropical guitar riffs, hard hitting drums and euphoric chord progressions . FSTVL ANTHMZ is comprised of 5 construction kits which contain loops, FX, drum one - shots, MIDI files and synth presets . Each kit is properly labeled with tempo and key for easy integration into your existing projects . Whether you want to create a quick mash - up or remix of your favorite tune to play out at your next show, all content has been designed with that summer festival vibe to make sure your sets standout . The additional presets and MIDI files easily help inspire new original tracks while mix and matching content from various kits yield ultimate flexibility . as an added bonus, sampler instruments have been included for Kontakt 5, Maschine 2.0, Logics’ EXS 24 and Reason NNXT . if you’re looking to produce content for those big Vegas daytime pool parties and or summer festivals then FSTVL ANTMZ from ADSR has exactly what you need .',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 30,
                'name' => 'HYPERCOLOR Presets for RC - 20',
                'labelName' => 'Dharma Studio',
                'price' => 119,
                'weight' => '16GB',
                'category' => 2,
                'labelTitle' => 'Dharma Studio',
                'Tag' => 'Vintage & Retro, FX, ADSR',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/03/ADSR-HYPERCOLOR-cover-500-1.png',
                'description' => '50 expertly designed textures and effects presets for XLN Audio’s RC - 20 Retro Color . Inspired by the 80s and 90s synth - pop, rock, new wave and electronic; designed for modern music . This preset pack includes a wide selection of creative textures that will literally transform your sounds from drums, keys, guitars and bass to your full mix . Check out the demo to hear some of them in action! HYPERCOLOR makes full use of RC - 20’s effect modules to give you instantly useable and infinitely fun and exciting presets that will put you in the mood to make music!',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 31,
                'name' => 'Electronica 2 - Presets for Arturia Pigments',
                'labelName' => 'Dharma Studio',
                'price' => 120,
                'weight' => '16GB',
                'category' => 2,
                'labelTitle' => 'Dharma Studio',
                'Tag' => 'Synths, ADSR',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/03/ADSR-Electronica-2-Cover-HQ-min-1-500x500.png',
                'description' => 'Experience music in full technicolour with a collection of presets for Arturia Pigments and add a new spectrum of depth, inspiration and colour to your music Electronica2 for Arturia Pigments is a follow up to our first pack of the same name . This volume goes deeper into our creative experiment with Pigments to inject innovation and imagination into the space in and around electronica, lo - fi, indie pop and contemporary R & B . Discover 99 original presets that will reinvigorate your spark for music - making and fill your project with a fresh new sound . From unique pads and new bass options to leads, plucks, sfx and a whole range of contemporary keys this collection promises to apply both the colour and shading you need to bring your music to life . Plus, as an added bonus, we’ve also included 4 full song kits taken from the demo so nothing is left out .',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 32,
                'name' => 'Blush - Harmonic Vocal Samples',
                'labelName' => 'Dharma Studio',
                'price' => 121,
                'weight' => '16GB',
                'category' => 1,
                'labelTitle' => 'Dharma Studio',
                'Tag' => 'Vocals, FX, ADSR',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/03/blush_ADSR_-Harmonic-Vocal-Samples-1.jpg',
                'description' => 'BLUSH – Harmonic Vocal Phrases includes 150 flirtatious vocal phrases from single words to full phrases running the full spectrum from sassy to sexy, flirty to undying love .Express your deepest desires with 150 love and lust themed harmonic vocals including a wide range of long phrases from “We’re meant for each other” and “It was more than love” to “you turn me inside out” and “I’m not alive until you call”; short phrases like “one heart”, “keeps me high” and “let’s make love”; down to single words including “love”, “lover” and “endless” . From lust to love or perhaps a broken heart, this pack is will help you pour your heart out to music . Professionally recorded and processed it’s ideal for everything from future pop to future bass and edm to ambient . BLUSH – Harmonic Vocal Phrases includes wet and dry versions of 150 original phrases(300 total) plus 2 bonus kits taken from the demo to help inspire the ultimate love song .',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 33,
                'name' => 'SHINBASHI FUTURE CHILL ASIA',
                'labelName' => 'Dharma Studio',
                'price' => 132,
                'weight' => '16GB',
                'category' => 1,
                'labelTitle' => 'Dharma Studio',
                'Tag' => 'ADSR, Ethnic, Organic, Future Bass',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/03/Shinbashi_1000x1000-1-500x500.jpg',
                'description' => 'Shinbashi – Future Chill Asia uses a combination of traditional Asian instruments, classic samplers such as the MPC 3000 along with the powerful synthesis within Serum has birthed a unique hybrid spin on Future Bass, R & B & Lo - Fi Chillout . Punchy drums, warm saturated basslines, funky leads, spaced out pads and beautiful melodic elements comprised of classic keys and traditional instruments from Asia round out Shinbashi to the fullest .',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 34,
                'name' => '909 Rhythm',
                'labelName' => 'Dharma Studio',
                'price' => 133,
                'weight' => '20GB',
                'category' => 2,
                'labelTitle' => 'Dharma Studio',
                'Tag' => 'ADSR, House, Vintage & Retro',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/03/ADSR-909-Rhythm-cover-hq-1-500x500.png',
                'description' => 'To celebrate 909 day and pay tribute to the undeniable impact the TR - 909 still has on the electronic music scene, ADSR has created: 909 – Rhythm . A collection of samples, loops and kits inspired by the past and designed for modern productions The sound of the TR - 909 is like a beacon that has led so many people from dance floor to dj’ing to making music . From Aphex Twin to Technotronic, Orbital to Derrick May and Daft Punk to Bjork – we just can’t name them all because the 909 is not just about beats it’s about the whole grooving package . Whether you’re working on Techno, House, or EDM; from classic anthems to entirely new beats, this truly unique collection will have you ready to get into the studio via the dance floor!',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 35,
                'name' => 'The Wraiths',
                'labelName' => 'Dharma Studio',
                'price' => 134,
                'weight' => '17GB',
                'category' => 1,
                'labelTitle' => 'Dharma Studio',
                'Tag' => 'ADSR, Cinematic, FX',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/03/ADSR-The-Wraiths-cover-hq-1-500x500.png',
                'description' => 'The Wraiths are here, can you hear them ? They have unfinished business and will haunt your music with atmospheres and sounds that though unseen, make their presence keenly felt .',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 36,
                'name' => 'LO - FIRE II',
                'labelName' => 'Dharma Studio',
                'price' => 135,
                'weight' => '20GB',
                'category' => 1,
                'labelTitle' => 'Dharma Studio',
                'Tag' => 'ADSR, Hip - Hop, Lo - Fi',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/03/LO-FIRE-II-Presets-Samples-Loops-1-500x500.jpg',
                'description' => 'Prepare for a journey that has no end as LO - FIRE II brings about the next stage of your musical evolution . After the success of the original LO - FIRE pack, fans were left wanting more and have been curious to know where the genre could go next . Today, LO - FIRE II opens a whole new chapter on Lofi, Downtempo Trap and Chill Hop and Electronica .',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 37,
                'name' => 'Warehouse Bass',
                'labelName' => 'Dharma Studio',
                'price' => 137,
                'weight' => '16GB',
                'category' => 3,
                'labelTitle' => 'Dharma Studio',
                'Tag' => 'ADSR, Bass House, Techno',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/03/ADSR-Warehouse-Bass-1-500x500.jpg',
                'description' => 'Dirty warehouse, hard hitting drums, and heavy low end subs with massive wobbles is the vibe in the latest release from ADSR, Warehouse Bass . A hybrid combination of Techno, Breaks and Wobble Bass House rounds out the sound elements in this release .',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 38,
                'name' => 'Nominated - Artist Inspired Samples, MIDI, Presets & Kits',
                'labelName' => 'Dharma Studio',
                'price' => 138,
                'weight' => '16GB',
                'category' => 1,
                'labelTitle' => 'Dharma Studio',
                'Tag' => 'ADSR, Electronica, Pop, R & B',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/03/ADSR-Nominated-cover-hq-2000-1-min-1-500x500.png',
                'description' => 'ADSR presents Nominated . A collection of artist - inspired sounds, samples and kits that give you the very best of today so you can create something groundbreaking tomorrow . It’s been an incredible 12 months – the world has changed and it’s often only the music that has gotten us through – both making it and listening to it .',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 39,
                'name' => 'Maad Decent Bass Party',
                'labelName' => 'Dharma Studio',
                'price' => 139,
                'weight' => '16GB',
                'category' => 2,
                'labelTitle' => 'Dharma Studio',
                'Tag' => 'ADSR, Trap, Moombahtoon, Dubstep',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/03/Maad-Decent-Bass-Party-1-500x500.png',
                'description' => 'Moombahton is alive and well taking the global festival stages by storm . This latest release from ADSR Sounds delivers the full experience with 5 earth - shaking construction kits each fully loaded with audio loops, MIDI files, one - shot samples and synth presets .',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 40,
                'name' => 'Deep House Sessions',
                'labelName' => 'Dharma Studio',
                'price' => 140,
                'weight' => '17GB',
                'category' => 2,
                'labelTitle' => ' Dharma Studio',
                'Tag' => 'Vocals, ADSR, Deep House',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/03/ADSR-Deep-House-Sessions-Cover-1-500x500.jpg',
                'description' => 'The production team at ADSR is back with with a brand new set of Deep House construction kits to elevate your production into the afterhours . Artists such as Duke Dumont, Claptone, Nore En Pure, Yotto, Milk & Sugar, EDX and Sofi Tukker are all sonically represented in this release . This pack comes with 5 construction kits filled with heavy sub basses, melodic chords, blissful leads, rhythmic drum loops and pitch shifted vocal stabs to satisfy any dance floor . Drum one - shots and MIDI files are included with every kit to allow maximum flexibility and rearrangement possibilities . Every kit has been properly labeled with key and tempo information .',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 41,
                'name' => 'R3c0nc3ive - Reimagine the 303',
                'labelName' => 'Dharma Studio',
                'price' => 141,
                'weight' => '16GB',
                'category' => 3,
                'labelTitle' => 'Dharma Studio',
                'Tag' => 'ADSR, Techno, Acid House',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/03/ADSR-R3C0NC3IVE-cover-hq-1-500x500.png',
                'description' => 'Ah the mighty Roland TB - 303 it’s unique acid sound is so iconic, so visceral, so … typecast . The distinctive sound and feeling of that squelching acid sound is so singular it can take over a track and send it back to the late 80s and 90s . Does it have to be that way ? Always up for a challenge, we asked ourselves – can we reconceive the 303 to hear it differently and create a new place for it in modern music ?',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 42,
                'name' => 'Reggaeton & Moombahtoon',
                'labelName' => 'AudioKaviar',
                'price' => 142,
                'weight' => '16GB',
                'category' => 1,
                'labelTitle' => 'AudioKaviar',
                'Tag' => 'Moombahtoon, AudioKaviar',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/03/AUDIOKAVIAR-05-Reggaeton-cover-1.jpg',
                'description' => 'AudioKaviar 05: Reggaeton brings a fiery latin vibe to urban and dance beats . Our aim is to provide a complete resource of assets for genres from Moombahton to Reggaeton and Dance Hall to Latin Hip Hop and Cubaton . At the core of this pack sit 35 Drum Racks supported by a prime selection of kits, loops, one - shots and presets to enhance your production workflow . We have made the most of Ableton’s Drum Racks function offering a range of unique racks from original drum racks to more creative selections including 808, Bass racks, Piano, Strings and synths, instrumental racks and more .',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 43,
                'name' => 'Hip Hop & Drill',
                'labelName' => 'AudioKaviar',
                'price' => 143,
                'weight' => '16GB',
                'category' => 3,
                'labelTitle' => 'AudioKaviar',
                'Tag' => 'AudioKaviar, Hip - Hop, Drill',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/03/AudioKaviar-04-Hip-Hop-Drill-cover-1-500x500.jpg',
                'description' => 'AudioKaviar 04: Hip Hop & Drill is a new vibe in the space between hip hop and drill, playing new sounds in classic ways . Make the familiar fresh again! Our aim is to provide a complete resource of assets for genres from hip hop, trap and lofi, drill to grime and garage . At the core of this pack sit 35 Drum Racks supported by a prime selection of kits, loops, one - shots and presets to enhance your production workflow . We have made the most of Ableton’s Drum Racks function offering a range of unique racks from original drum racks to more creative selections including 808, Bass racks, Piano, Strings and synths, instrumental racks and more .',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 44,
                'name' => 'Chill Hop & Lo - Fi',
                'labelName' => 'AudioKaviar',
                'price' => 148,
                'weight' => '16GB',
                'category' => 2,
                'labelTitle' => 'AudioKaviar',
                'Tag' => 'AudioKaviar, Hip - Hop, Lo - Fi',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/03/AudioKaviar-CHILL-HOP-LO-FI_500.jpg',
                'description' => 'Chill Hop & Lo - Fi takes you on a unique musical journey through the depths of creativity . Ride the musical currents from warm melodic vibes to cool, immersive synths and solid beats to keep you on course .',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 45,
                'name' => 'Trap Soul & R & B',
                'labelName' => 'Dharma Studio',
                'price' => 147,
                'weight' => '16GB',
                'category' => 3,
                'labelTitle' => 'Dharma Studio',
                'Tag' => 'R & B, AudioKaviar, Trap, Funk & Soul',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/03/AUDIOKAVIAR-02-TRAP-SOUL-RB-500.jpg',
                'description' => 'Our aim is to provide a complete resource of assets for genres including contemporary R & B, soulful Trap and Lofi . At the core of this pack sit 25 Drum Racks supported by a prime selection of kits, loops, one - shots and presets to enhance your production workflow . We have made the most of Ableton’s Drum Racks function offering a range of unique racks from original drum racks to more creative selections including 6 Chord racks(including 2 Lofi chord racks), 3 808 racks, bass guitar rack, Reese Bass racks, plucks, pads, bells and more .',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 46,
                'name' => 'Indie Pop & Electronica',
                'labelName' => 'AudioKaviar',
                'price' => 26,
                'weight' => '16GB',
                'category' => 1,
                'labelTitle' => 'AudioKaviar',
                'Tag' => 'AudioKaviar, Electronica, Pop, Dance Pop',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/03/AUDIOKAVIAR-01-INDIE-POP-ELECTRONICA-500.jpg',
                'description' => 'Our aim is to provide a complete resource of assets for genres including indie pop, electronica and contemporary R & B . At the core of this pack sit 25 Drum Racks supported by a prime selection of kits, loops, one - shots and presets to enhance your production workflow . We have made the most of Ableton’s Drum Racks function offering a range of unique racks from original drum racks to more creative selections including an 808 rack, bass guitar rack, a rack for background melodies, a synth vs 808 rack, there’s even a space bells from the future rack!',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 47,
                'name' => 'Rouge',
                'labelName' => 'GHST PRJK',
                'price' => 27,
                'weight' => '16GB',
                'category' => 2,
                'labelTitle' => 'GHST PRJK',
                'Tag' => 'Lo - Fi, GHST PRJKT, Hip - Hop, Electronica',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/03/Rouge_1000x1000-1-500x500.jpg',
                'description' => 'The production team at GHST PRJKT have returned with a new spin on Electronic Hip Hop and Chilled Out Lo - Fi in their latest release Rouge .',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 48,
                'name' => 'Grander',
                'labelName' => 'GHST PRJKT',
                'price' => 28,
                'weight' => '16GB',
                'category' => 3,
                'labelTitle' => 'GHST PRJKT',
                'Tag' => 'GHST PRJKT, Pop, Dance Pop',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/03/GHST-PRJKT-Your-Turn-serum-loops-samples-cover-1.png',
                'description' => 'In just a few short years he’s taken a seat at the music industry’s head table, we felt it was the perfect time to create a sound set inspired by Lil Baby .',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 49,
                'name' => 'Your Turn',
                'labelName' => 'GHST PRJKT',
                'price' => 33,
                'weight' => '17GB',
                'category' => 2,
                'labelTitle' => 'GHST PRJKT',
                'Tag' => 'GHST PRJKT, Hip - Hop, Trapp',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/03/AUDIOKAVIAR-01-INDIE-POP-ELECTRONICA-500.jpg',
                'description' => 'Our aim is to provide a complete resource of assets for genres including indie pop, electronica and contemporary R & B . At the core of this pack sit 25 Drum Racks supported by a prime selection of kits, loops, one - shots and presets to enhance your production workflow . We have made the most of Ableton’s Drum Racks function offering a range of unique racks from original drum racks to more creative selections including an 808 rack, bass guitar rack, a rack for background melodies, a synth vs 808 rack, there’s even a space bells from the future rack!',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ], [
                'id' => 50,
                'name' => 'Awe',
                'labelName' => 'GHST PRJKT',
                'price' => 22,
                'weight' => '16GB',
                'category' => 3,
                'labelTitle' => 'GHST PRJKT',
                'Tag' => 'GHST PRJKT, Organic, Pop',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/03/GHST-PRJKT-Awe-cover-hq-1-500x500.png',
                'description' => 'With a slew of hit albums and a sound that wiggles its way into even the staunchest of anti - pop listener’s brains, it seems like everything he touches turns to platinum . From posting covers on YouTube to topping the Billboard hottest 100 almost every time he puts out a song, we thought it was a good time to create a soundbank inspired by Shawn Mendes From Stitches to Treat You Better to the dominating hit Senorita through to his latest album Wonder, Shawn Mendes’ musical style is both inspiring and 100 % relatable . His production choices are always on point which has led his music to go from strength to strength .',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 51,
                'name' => 'Like This',
                'labelName' => 'GHST PRJKT',
                'price' => 91,
                'weight' => '16GB',
                'category' => 2,
                'labelTitle' => 'GHST PRJKT',
                'Tag' => 'GHST PRJKT, Pop, Dance Pop',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/03/GHST-PRJKT-Like-This-serum-loops-samples-cover-fin-1.jpg',
                'description' => 'This year has seen Korean Pop Music or “KPop” come into its own with groups like Black Pink and BTS making it into top 10 charts around the world . Behind the beautiful people, epic dance routines, and cinematic level music videos sits talent, skill, and a dedicated work ethic, everything it takes to make it in this business . That’s why we wanted to create a bank of sounds that will bring a KPop attitude to your productions',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 52,
                'name' => 'The Feels - Funkwave Elements',
                'labelName' => 'GHST PRJKT',
                'price' => 88,
                'weight' => '16GB',
                'category' => 1,
                'labelTitle' => 'GHST PRJKT',
                'Tag' => 'Synthwave, GHST PRJKT, Funk & Soul, Vintage & Retro',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/03/ADSR_TheFeels_1000x1000-1-500x500.jpg',
                'description' => 'Our aim is to provide a complete resource of assets for genres including indie pop, electronica and contemporary R & B . At the core of this pack sit 25 Drum Racks supported by a prime selection of kits, loops, one - shots and presets to enhance your production workflow . We have made the most of Ableton’s Drum Racks function offering a range of unique racks from original drum racks to more creative selections including an 808 rack, bass guitar rack, a rack for background melodies, a synth vs 808 rack, there’s even a space bells from the future rack!',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 53,
                'name' => 'Boombox [Sound Pack]',
                'labelName' => 'Dharma Studio',
                'price' => 77,
                'weight' => '18GB',
                'category' => 3,
                'labelTitle' => 'Dharma Studio',
                'Tag' => 'Slap House, Dance, Dharma Studio, Samples',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/02/BOOMBOXSOUNDPACK-500x500.jpg',
                'description' => 'This Sound Pack is filled with that classic Indie Dance flavor that will give aspiring producers the creativity and inspiration they need to make their next big dance hit!The Indie Dance Sound Pack gives you access to Drum Sounds, FX sounds, and other types of exclusive loops that you cannot find anywhere else!All Dharma sound packs are 100 % royalty - free and compatible with any DAW or sampler .',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 54,
                'name' => 'Balma [Sound Pack]',
                'labelName' => 'Dharma Studio',
                'price' => 66,
                'weight' => '16GB',
                'category' => 3,
                'labelTitle' => 'Dharma Studio',
                'Tag' => 'Dance',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2022/07/BALMA-500x500.jpg',
                'description' => 'Enjoy this free sound pack featuring samples from Dronark s Balma (feat . Mitika Kanwar). All Dharma sound packs are 100 % royalty - free and compatible with any DAW . Includes: -3 Drum Shots / Loops - 4 Drum Fills - 5 Vocals - 2 Bass Shots - 2 FX / Impacts',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 55,
                'name' => 'Indie Dance',
                'labelName' => 'Dharma Studio',
                'price' => 11,
                'weight' => '16GB',
                'category' => 1,
                'labelTitle' => 'Dharma Studio',
                'Tag' => 'Dance, Dharma Studio, Sample Pack',
                'thumbnail' => 'https://www.dharmaworldwide.com/wp-content/uploads/2021/09/Indie-Dance_001-500x500.jpg',
                'description' => 'Our aim is to provide a complete resource of assets for genres including indie pop, electronica and contemporary R & B . At the core of this pack sit 25 Drum Racks supported by a prime selection of kits, loops, one - shots and presets to enhance your production workflow . We have made the most of Ableton’s Drum Racks function offering a range of unique racks from original drum racks to more creative selections including an 808 rack, bass guitar rack, a rack for background melodies, a synth vs 808 rack, there’s even a space bells from the future rack!',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'id' => 56,
                'name' => 'ARMAA [Sample Pack]',
                'labelName' => 'Revealed',
                'price' => 88,
                'weight' => '12GB',
                'category' => 3,
                'labelTitle' => 'Revealed',
                'Tag' => 'DEEP HOUSE,MELODIC HOUSE',
                'thumbnail' => 'https://www.revealedrecordings.com/uploads/image/621e140ff50187514f118c44.jpg',
                'description' => 'Various sounds, effects, loops, presets, and more included in this Sample Pack by ARMAA!',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 57,
                'name' => 'NARA',
                'labelName' => 'Monstercat',
                'price' => 72,
                'weight' => '17GB',
                'category' => 1,
                'labelTitle' => 'Monstercat',
                'Tag' => 'PROFF',
                'thumbnail' => 'https://cdx.monstercat.com/?encoding=webp&url=https%3A%2F%2Fwww.monstercat.com%2Frelease%2FMCS1486%2Fcover%3Fe2a06d43-8732-413e-8e69-178e0ca75922&width=600',
                'description' => 'Silk — Gold Early Access',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 58,
                'name' => 'SLIP AWAY',
                'labelName' => 'Monstercat',
                'price' => 12,
                'weight' => '20GB',
                'category' => 2,
                'labelTitle' => 'Monstercat',
                'Tag' => 'ARLOW,KID SPIRIT',
                'thumbnail' => 'https://cdx.monstercat.com/?encoding=webp&url=https%3A%2F%2Fwww.monstercat.com%2Frelease%2FMCS1485%2Fcover%3F30ccb7e7-5ea0-4118-8358-e85c987aa92a&width=600',
                'description' => 'Instinct — Released October 18, 2022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 59,
                'name' => 'DILEMMA',
                'labelName' => 'Monstercat',
                'price' => 31,
                'weight' => '25GB',
                'category' => 1,
                'labelTitle' => 'Monstercat',
                'Tag' => 'STONEBANK,BIANCA',
                'thumbnail' => 'https://https://cdx.monstercat.com/?encoding=webp&url=https%3A%2F%2Fwww.monstercat.com%2Frelease%2FMCS1484%2Fcover%3F979ad058-fe44-4681-9702-c3629895b494&width=600',
                'description' => 'Uncaged — Released October 17, 2022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 60,
                'name' => 'COLLIDE',
                'labelName' => 'Monstercat',
                'price' => 41,
                'weight' => 'Monstercat',
                'category' => 3,
                'labelTitle' => 'Monstercat',
                'Tag' => 'YULA',
                'thumbnail' => 'https://cdx.monstercat.com/?encoding=webp&url=https%3A%2F%2Fwww.monstercat.com%2Frelease%2FMCS1483%2Fcover%3F764d84ae-fe56-4584-b5ce-f0ea4731fe6e&width=600',
                'description' => 'Instinct — Released October 14, 2022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 61,
                'name' => 'SKYLINE',
                'labelName' => 'Monstercat',
                'price' => 51,
                'weight' => '12GB',
                'category' => 2,
                'labelTitle' => 'Monstercat',
                'Tag' => 'MANGO',
                'thumbnail' => 'https://cdx.monstercat.com/?encoding=webp&url=https%3A%2F%2Fwww.monstercat.com%2Frelease%2FMCS1482%2Fcover%3Fe747adc0-f13d-4fa4-a1c7-3658ac35f2f2&width=600',
                'description' => 'Silk — Released October 14, 2022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 62,
                'name' => 'INVANE',
                'labelName' => 'Monstercat',
                'price' => 61,
                'weight' => '12GB',
                'category' => 1,
                'labelTitle' => 'Monstercat',
                'Tag' => 'SPAG HEDDY,VIPERACTIVE',
                'thumbnail' => 'https://cdx.monstercat.com/?encoding=webp&url=https%3A%2F%2Fwww.monstercat.com%2Frelease%2FMCS1481%2Fcover%3F22735169-aa43-487e-ae44-5979b39848a3&width=600',
                'description' => 'Uncaged — Released October 13, 2022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 63,
                'name' => 'THE LOST ANCIENT CHARM',
                'labelName' => 'Monstercat',
                'price' => 71,
                'weight' => '12GB',
                'category' => 2,
                'labelTitle' => 'Monstercat',
                'Tag' => 'FORTY CATS,ARENTIS',
                'thumbnail' => 'https://cdx.monstercat.com/?encoding=webp&url=https%3A%2F%2Fwww.monstercat.com%2Frelease%2FMCEP318%2Fcover%3F77d3dd6f-7d9b-40b6-b22d-bf93f6a419f9&width=600',
                'description' => 'Silk — Released October 12, 2022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 64,
                'name' => 'OCTOBER',
                'labelName' => 'Monstercat',
                'price' => 81,
                'weight' => '12GB',
                'category' => 1,
                'labelTitle' => 'Monstercat',
                'Tag' => 'LEAH CULVER',
                'thumbnail' => 'https://cdx.monstercat.com/?encoding=webp&url=https%3A%2F%2Fwww.monstercat.com%2Frelease%2FMCS1480%2Fcover%3Faf531a3e-168b-4209-b794-15300ae42d4c&width=600',
                'description' => 'Instinct — Released October 11, 2022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 65,
                'name' => 'DOUBLE TAP',
                'labelName' => 'Monstercat',
                'price' => 91,
                'weight' => '12GB',
                'category' => 3,
                'labelTitle' => 'Monstercat',
                'Tag' => 'GOING QUANTUM,HAYVE',
                'thumbnail' => 'https://cdx.monstercat.com/?encoding=webp&url=https%3A%2F%2Fwww.monstercat.com%2Frelease%2FMCS1479%2Fcover%3Ffb07694f-ce2e-44bb-9c8a-ec753e888600&width=600',
                'description' => 'Uncaged — Released October 10, 2022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 66,
                'name' => 'HOPEFUL',
                'labelName' => 'Monstercat',
                'price' => 22,
                'weight' => '12GB',
                'category' => 2,
                'labelTitle' => 'Monstercat',
                'Tag' => 'BANAATI,BRANDON MIGNACCA',
                'thumbnail' => 'https://cdx.monstercat.com/?encoding=webp&url=https%3A%2F%2Fwww.monstercat.com%2Frelease%2FMCS1477%2Fcover%3Fa6d6373a-bc09-4d8e-89fd-9673e8c3bf90&width=600',
                'description' => 'Silk — Released October 7, 2022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 67,
                'name' => 'MIRROR',
                'labelName' => 'Monstercat',
                'price' => 32,
                'weight' => '12GB',
                'category' => 1,
                'labelTitle' => 'Monstercat',
                'Tag' => 'SABAI,DANNI CARRA',
                'thumbnail' => 'https://cdx.monstercat.com/?encoding=webp&url=https%3A%2F%2Fwww.monstercat.com%2Frelease%2FMCS1478%2Fcover%3Faceac731-c76f-4831-8b95-626b2673344b&width=600',
                'description' => 'Instinct — Released October 7, 2022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 68,
                'name' => 'THE DEAD MARCH',
                'labelName' => 'Monstercat',
                'price' => 42,
                'weight' => '12GB',
                'category' => 3,
                'labelTitle' => 'Monstercat',
                'Tag' => 'SULLIVAN KING,RAY VOLPE',
                'thumbnail' => 'https://cdx.monstercat.com/?encoding=webp&url=https%3A%2F%2Fwww.monstercat.com%2Frelease%2FMCS1476%2Fcover%3Fcb3341de-cb62-4b09-a985-d3425f13985c&width=600',
                'description' => 'Uncaged — Released October 6, 2022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 69,
                'name' => 'KARIBU',
                'labelName' => 'Monstercat',
                'price' => 52,
                'weight' => '12GB',
                'category' => 2,
                'labelTitle' => 'Monstercat',
                'Tag' => 'VINTAGE,MORELLI',
                'thumbnail' => 'https://cdx.monstercat.com/?encoding=webp&url=https%3A%2F%2Fwww.monstercat.com%2Frelease%2FMCEP317%2Fcover%3Ff2042cbd-3dfe-4af6-8b0c-049d36a86a1d&width=600',
                'description' => 'Silk — Released October 5, 2022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 70,
                'name' => 'OUT OF THE DARK',
                'labelName' => 'Monstercat',
                'price' => 62,
                'weight' => '12GB',
                'category' => 1,
                'labelTitle' => 'Monstercat',
                'Tag' => 'NO MANA',
                'thumbnail' => 'https://cdx.monstercat.com/?encoding=webp&url=https%3A%2F%2Fwww.monstercat.com%2Frelease%2FMCS1475%2Fcover%3Fb3401973-0f10-4715-9890-3e91bc9b279e&width=600',
                'description' => 'Instinct — Released October 4, 2022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 71,
                'name' => 'RAD',
                'labelName' => 'Monstercat',
                'price' => 18,
                'weight' => '12GB',
                'category' => 3,
                'labelTitle' => 'Monstercat',
                'Tag' => 'TOKYO MACHINE',
                'thumbnail' => 'https://cdx.monstercat.com/?encoding=webp&url=https%3A%2F%2Fwww.monstercat.com%2Frelease%2FMCS1474%2Fcover%3F27ff8ac1-02db-4f60-b0f6-14e716912c5e&width=600',
                'description' => 'Uncaged — Released October 3, 2022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 72,
                'name' => 'RENAISSANCE',
                'labelName' => 'Monstercat',
                'price' => 82,
                'weight' => '12GB',
                'category' => 2,
                'labelTitle' => 'Monstercat',
                'Tag' => 'OCULA,LUKE COULSON',
                'thumbnail' => 'https://cdx.monstercat.com/?encoding=webp&url=https%3A%2F%2Fwww.monstercat.com%2Frelease%2FMCEP316%2Fcover%3Ff0e88da3-76cf-4ab7-8bf9-35951b30c878&width=600',
                'description' => 'Silk — Released September 30, 2022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 73,
                'name' => 'UNBREAKABLE',
                'labelName' => 'Monstercat',
                'price' => 92,
                'weight' => '12GB',
                'category' => 1,
                'labelTitle' => 'Monstercat',
                'Tag' => 'HOAPROX,BIANCA',
                'thumbnail' => 'https://cdx.monstercat.com/?encoding=webp&url=https%3A%2F%2Fwww.monstercat.com%2Frelease%2FMCS1473%2Fcover%3Fe2426561-dd8f-4eb6-aa48-8955557fce3d&width=600',
                'description' => 'Silk — Released September 30, 2022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 74,
                'name' => 'FULL ASSAULT / ALL THAT U WANT',
                'labelName' => 'Monstercat',
                'price' => 38,
                'weight' => '12GB',
                'category' => 3,
                'labelTitle' => 'Monstercat',
                'Tag' => 'VARIEN,PSYLLA',
                'thumbnail' => 'https://cdx.monstercat.com/?encoding=webp&url=https%3A%2F%2Fwww.monstercat.com%2Frelease%2FMCEP315%2Fcover%3F500b82d6-160d-44a8-acb9-8b8b01abfc62&width=600',
                'description' => 'Uncaged — Released September 29, 2022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 75,
                'name' => 'HAZE',
                'labelName' => 'Monstercat',
                'price' => 48,
                'weight' => '12GB',
                'category' => 2,
                'labelTitle' => 'Monstercat',
                'Tag' => 'LAR',
                'thumbnail' => 'https://cdx.monstercat.com/?encoding=webp&url=https%3A%2F%2Fwww.monstercat.com%2Frelease%2FMCEP314%2Fcover%3Ffd9821ad-39a0-4bd9-98e6-e00efff061d9&width=600',
                'description' => 'Silk — Released September 28, 2022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 76,
                'name' => 'JOURNEY',
                'labelName' => 'Monstercat',
                'price' => 58,
                'weight' => '12GB',
                'category' => 1,
                'labelTitle' => 'Monstercat',
                'Tag' => 'YETEP,KLAXX',
                'thumbnail' => 'https://cdx.monstercat.com/?encoding=webp&url=https%3A%2F%2Fwww.monstercat.com%2Frelease%2FMCS1472%2Fcover%3F0d253c01-08b1-4074-afdc-c75dab40fa54&width=600',
                'description' => 'Instinct — Released September 27, 2022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 77,
                'name' => 'SELL YOUR SOUL',
                'labelName' => 'Monstercat',
                'price' => 68,
                'weight' => '12GB',
                'category' => 3,
                'labelTitle' => 'Monstercat',
                'Tag' => 'SLIPPY,TYNAN',
                'thumbnail' => 'https://cdx.monstercat.com/?encoding=webp&url=https%3A%2F%2Fwww.monstercat.com%2Frelease%2FMCS1471%2Fcover%3F363243cf-d5ce-4a1c-beac-aba00689a6e4&width=600',
                'description' => 'Uncaged — Released September 26, 2022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 78,
                'name' => 'Hardwell Sylenth1 Soundset Bundle',
                'labelName' => 'Revealed',
                'price' => 78,
                'weight' => '12GB',
                'category' => 2,
                'labelTitle' => 'Revealed',
                'Tag' => 'BIG ROOM,BUNDLE,EDM,PROGRESSIVE HOUSE',
                'thumbnail' => 'https://www.revealedrecordings.com/uploads/image/5cd03b02c6e1900f223293e3.jpg',
                'description' => 'This bundle offers Vol. 1 and Vol. 2 of Hardwell’s Soundsets for Sylenth1. Hardwell’s signature big room sound is at your fingertips!',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 79,
                'name' => 'Maddix presents Sounds Of The Tribe Vol. 1',
                'labelName' => 'Revealed',
                'price' => 98,
                'weight' => '12GB',
                'category' => 1,
                'labelTitle' => 'Revealed',
                'Tag' => 'BIG ROOM,TECHNO',
                'thumbnail' => 'https://www.revealedrecordings.com/uploads/image/60b82254c889525aa1265bd2.jpg',
                'description' => 'With a signature sound helping to redefine modern EDM and influence the rise of creative exploration, Maddix turns his attention to the next generation of electronic producers. Fusing his style of big room, techno, and old school rave, you’ll find the sounds from his latest and upcoming releases, containing all the ingredients to create the signature Sound of the Tribe.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 80,
                'name' => 'Revealed Ryos Serum Soundset Vol. 1',
                'labelName' => 'Revealed',
                'price' => 108,
                'weight' => '12GB',
                'category' => 3,
                'labelTitle' => 'Revealed',
                'Tag' => 'BIG ROOM,MAINSTAGE,PROGRESSIVE HOUSE',
                'thumbnail' => 'https://www.revealedrecordings.com/uploads/image/5fbbf5066c775d650219eda3.jpg',
                'description' => 'As one of Revealed is most talented producers, Ryos has become prominent for his modern progressive house sound . Now, Ryos is releasing 134 of his presets for Serum, where you will find sounds from his latest and upcoming releases, allowing producers to recreate the signature Ryos sound.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 81,
                'name' => 'REGGIO Soundset Mega Pack Vol. 3',
                'labelName' => 'Revealed',
                'price' => 118,
                'weight' => '12GB',
                'category' => 2,
                'labelTitle' => 'Revealed',
                'Tag' => 'FUTUREBASS',
                'thumbnail' => 'https://www.revealedrecordings.com/uploads/image/602a6a8a6b0685179f36a424.jpg',
                'description' => 'REGGIO returns for the third installment of his Soundset Mega Pack Series.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 82,
                'name' => 'Blackcode Sylenth1 Soundset Vol. 1',
                'labelName' => 'Revealed',
                'price' => 128,
                'weight' => '12GB',
                'category' => 1,
                'labelTitle' => 'Revealed',
                'Tag' => 'PROGRESSIVE HOUSE',
                'thumbnail' => ';https://www.revealedrecordings.com/uploads/image/60108fe8c93779193f3ee817.jpg',
                'description' => 'With a hit-studded slate of Revealed releases, Blackcode has become a label favorite for his melodic progressive house sound.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 83,
                'name' => 'The Best (Logic Pro X Project File)',
                'labelName' => 'Revealed',
                'price' => 138,
                'weight' => '12GB',
                'category' => 3,
                'labelTitle' => 'Revealed',
                'Tag' => 'BASS HOUSE',
                'thumbnail' => 'https://www.revealedrecordings.com/uploads/image/6294ce8bded4c936a40163fa.jpg',
                'description' => 'Take a look inside R I V I E R A s Logic Pro Project File of their song The Best, and see which tricks, plug-ins, and techniques they used!',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 84,
                'name' => 'Flex (FL Studio Project)',
                'labelName' => 'Revealed',
                'price' => 148,
                'weight' => '12GB',
                'category' => 2,
                'labelTitle' => 'Revealed',
                'Tag' => 'TechnoS',
                'thumbnail' => 'https://www.revealedrecordings.com/uploads/image/604f78fa1869ad3e2e3bf041.jpg',
                'description' => 'The FL Studio Project of "Flex" by The Cabas is available NOW!',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 85,
                'name' => 'I am In Love(FL Studio Project)',
                'labelName' => 'Revealed',
                'price' => 13,
                'weight' => '12GB',
                'category' => 1,
                'labelTitle' => 'Revealed',
                'Tag' => 'Techno',
                'thumbnail' => 'https://www.revealedrecordings.com/uploads/image/5fa938a1aa958153d84535af.jpg',
                'description' => 'The FL Studio Project of "I am In Love" by NDR8 & Skytters is available now for FREE download!',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 86,
                'name' => 'Eyes (FL Studio Project)',
                'labelName' => 'Revealed',
                'price' => 23,
                'weight' => '12GB',
                'category' => 3,
                'labelTitle' => 'Revealed',
                'Tag' => 'Techno',
                'thumbnail' => 'https://www.revealedrecordings.com/uploads/image/5f9943e68d16662e2e5af820.jpg',
                'description' => 'The FL Studio Project of Eyes by Leo Teran & Zheno feat. Nino Lucarelli is available now for FREE download!',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 87,
                'name' => 'Revealed Massive Signature Soundset Vol. 1',
                'labelName' => 'Revealed',
                'price' => 33,
                'weight' => '12GB',
                'category' => 2,
                'labelTitle' => 'Revealed',
                'Tag' => 'BIG ROOM,EDM,PROGRESSIVE HOUSE',
                'thumbnail' => 'https://www.revealedrecordings.com/uploads/image/597b35ebc6e1902c8f77c10b.jpg',
                'description' => 'REVEALED MASSIVE SIGNATURE SOUNDSET VOL. 1 Revealed Massive Signature Soundset Vol. 1 is a collection of 128 presets for your next Revealed track. Youíll find a spectacular array of basses, leads, pads, and plucks - all easily customizable to fit into your music. Additionally, each preset is assigned all eight macro controls programmed to give you an abundance of inspiring performance shaping features. You have everything right at your fingertips and the ability to select a variety of new and advanced presets found inside existing and upcoming Revealed tracks.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 88,
                'name' => 'Start Move (Sample Pack)',
                'labelName' => 'Revealed',
                'price' => 43,
                'weight' => '12GB',
                'category' => 1,
                'labelTitle' => 'Revealed',
                'Tag' => 'PSY TRANCE',
                'thumbnail' => 'https://www.revealedrecordings.com/uploads/image/6329c890d53b05ff30021422.jpg',
                'description' => 'Various sounds, effects, loops, and more included in this Sample Pack by Maski & Banga!',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 89,
                'name' => 'Revealed Halloween Horror [2017 Edition] [Credits]',
                'labelName' => 'Revealed',
                'price' => 53,
                'weight' => '12GB',
                'category' => 3,
                'labelTitle' => 'Revealed',
                'Tag' => 'Electronic',
                'thumbnail' => 'https://www.revealedrecordings.com/uploads/image/59e1be5ac6e1903e9545c5ca.jpg',
                'description' => 'Welcome to Revealed Halloween Horror. Explore the bloodcurdling sonic elements inside Halloween Horror with 315 hair-raising samples and 32 spine-chilling presets for Sylenth1. We’ve captured a wide spectrum of sounds; from unnerving atmospheric drones, menacing FX, demonic impacts, various instruments (including organs, pianos, and strings) and a vast collection of frightening vocals – to breaths, insane clowns, hellish demons, eerie ghosts, possessed little girls, and cruel witches – so you can imagine and create your own Horror scene.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 90,
                'name' => 'Revealed Festival Kits Vol. 2 [Credits]',
                'labelName' => 'Revealed',
                'price' => 63,
                'weight' => '12GB',
                'category' => 2,
                'labelTitle' => 'Revealed',
                'Tag' => 'BIG ROOM,EDM,MAINSTAGE',
                'thumbnail' => 'https://www.revealedrecordings.com/uploads/image/5a32df8ac6e1904db40c61b8.jpg',
                'description' => 'Revealed Festival Kits Vol. 2 is a collection of 5 construction kits ready to use in your next Revealed track. Each kit includes the WAV files of all the elements of the track; from bass, synths, leads, kicks, fills, fx, claps, percussion, and more. In addition, each Kit contains the MIDI files of all the melodic and bass elements, so you can easily manipulate your favorite sounds and construct it just the way you want it. To speed your workflow, each Kit is labeled with its root key and BPM information.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 91,
                'name' => 'Revealed Festival Kits Vol. 1 [Credits]',
                'labelName' => 'Revealed',
                'price' => 73,
                'weight' => '12GB',
                'category' => 1,
                'labelTitle' => 'Revealed',
                'Tag' => 'BIG ROOM,EDM,MAINSTAGE',
                'thumbnail' => 'https://www.revealedrecordings.com/uploads/image/59c53879c6e19022eb1ad55f.jpg',
                'description' => 'Revealed Festival Kits Vol. 1 is a collection of 5 construction kits ready to use in your next Revealed track. Each kit includes the WAV files of all the elements of the track; from bass, synths, leads, kicks, fills, fx, claps, percussion, and more. In addition, each Kit contains the MIDI files of all the melodic and bass elements, so you can easily manipulate your favorite sounds and construct it just the way you want it. To speed your workflow, each Kit is labeled with its root key and BPM information.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 92,
                'name' => 'Revealed Radar Sample Pack Vol. 2',
                'labelName' => 'Revealed',
                'price' => 83,
                'weight' => '12GB',
                'category' => 3,
                'labelTitle' => 'Revealed',
                'Tag' => 'FUTUREBASS',
                'thumbnail' => 'https://www.revealedrecordings.com/uploads/image/608c2cf2ca945506c31832f2.jpg',
                'description' => 'Revealed proudly presents: Revealed Radar Sample Pack Vol. 2. A collective free sample pack of some of Revealed is very own talented music producers such as Agus Zack, Basstian, Chester Young, HAVOQ, Kevin Brand, Mr . Sid and Wyko!',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 93,
                'name' => 'Revealed Producer Starter Pack Vol . 1',
                'labelName' => 'Revealed',
                'price' => 93,
                'weight' => '12GB',
                'category' => 2,
                'labelTitle' => 'Revealed',
                'Tag' => 'BIG ROOM,EDM,PROGRESSIVE HOUSE',
                'thumbnail' => 'https://www.revealedrecordings.com/uploads/image/5b076b18c6e19009df33bf5a.jpg',
                'description' => 'Welcome to Revealed Producer Starter Pack Vol. 1; a FREE sample library for all aspiring and seasoned pro is alike who want to recreate the signature Revealed Recordings sound . ',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 94,
                'name' => 'Revealed Fight Club Vol . 1 [Credits]',
                'labelName' => 'Revealed',
                'price' => 103,
                'weight' => '12GB',
                'category' => 1,
                'labelTitle' => 'Revealed',
                'Tag' => 'ACID,EDM,TECHNO',
                'thumbnail' => 'https://www.revealedrecordings.com/uploads/image/59a01d33c6e1905398458645.jpg',
                'description' => 'Welcome to the Revealed Fight Club. Explore the sonic elements inside the Fight Club with 200 samples and 32 heavy hitting presets for Sylenth1. We’ve captured a wide spectrum of sounds; from jabbing kicks, striking ring bells, pounding snares, beating percussion, and smashing punching bags – to announcer commentary, reactions, breaths, and fighter taunts – so you can imagine and create your own Fight Club scene.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id' => 95,
                'name' => 'LOSING MY MIND',
                'labelName' => 'Monstercat',
                'price' => 113,
                'weight' => '12GB',
                'category' => 3,
                'labelTitle' => 'Monstercat',
                'Tag' => 'BOUND TO DIVIDE,JULIAN GRAY,AVRII CASTLE',
                'thumbnail' => 'https://cdx.monstercat.com/?encoding=webp&url=https%3A%2F%2Fwww.monstercat.com%2Frelease%2FMCS1470%2Fcover%3F13883425-ed52-41fc-a0a2-426b5df61a58&width=600',
                'description' => 'Silk — Released September 23, 2022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 96,
                'name' => 'MIDNIGHT',
                'labelName' => 'Monstercat',
                'price' => 123,
                'weight' => '12GB',
                'category' => 2,
                'labelTitle' => 'Monstercat',
                'Tag' => 'MICK MAZOO',
                'thumbnail' => 'https://cdx.monstercat.com/?encoding=webp&url=https%3A%2F%2Fwww.monstercat.com%2Frelease%2FMCS1469%2Fcover%3Fbfe8e19b-4a2a-499b-84c7-7f774bcd111f&width=600',
                'description' => 'Instinct — Released September 23, 2022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
